### ISSUE TITLE
Interactivity lost on cached Container holding Shape when graphics is cleared

### ISSUE THREAD

**Issue by danzen** [CreateJS/EaselJS#1000]
### TODO
- [x] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

- [x] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

### Issue Details
* Version used (Ex; 1.0): 

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

* Do you know of any workarounds?

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by danzen** [comment]
`var container = new createjs.Container();
    stage.addChild(container);
    var shape = new createjs.Shape();
    container.addChild(shape);
    shape.graphics.f(red).dr(0,0,100,100)
    container.cache(0, 0, 100, 100);
    // shape.setBounds(0, 0, 100, 100); // does not help
    // container.setBounds(0, 0, 100, 100); // does not help
    shape.graphics.clear();
    container.on("mousedown", function () {
        // will not trigger if we clear graphics
        // will trigger if we do not clear graphics
        console.log("hi");
    });
`

**Comment by danzen** [comment]
Woot!  Issue 1000!

**Comment by danzen** [comment]
This offers a work-around...  The reason for using the container in the first place is that I have other things I want to add in there to cache as well.

```
    var container = new createjs.Container();
    stage.addChild(container);
    var shape = new createjs.Shape();
    container.addChild(shape);
    shape.graphics.f(red).dr(0,0,100,100)
    container.cache(0, 0, 100, 100);
    
    var bitmap = new createjs.Bitmap(container.cacheCanvas);
    container.addChild(bitmap);
    container.uncache();
    
    // shape.setBounds(0, 0, 100, 100); // does not help
    // container.setBounds(0, 0, 100, 100); // does not help
    shape.graphics.clear();
    container.on("mousedown", function () {
        // will not trigger if we clear graphics
        // will trigger if we do not clear graphics
        console.log("hi");
    });
```

**Comment by lannymcnie** [comment]
Confirmed on 0.8.2 as well, so it's not an issue with the updated BitmapCache changes in 1.0

**Comment by lannymcnie** [comment]
Ah, makes sense. The `isVisible()` check for Shapes looks for empty graphics. It should probably check for a cache as well.

```
var hasContent = this.cacheCanvas || (this.graphics && !this.graphics.isEmpty());
```

**Comment by gskinner** [comment]
In short, we either need to look at a cached Container as a flat object, or as a collection of children. Doing the former loses all mouse interaction for the children, which I fear would break existing content.

I've written a "fix" that will only treat it as a flat object if we're doing a mouse test and the container (or it's parent) are capturing the mouse event. This works, but it will cause changes in the event target that is returned (it will go from being a child of the container, to the container itself).

I'm a little wary about rolling out this change, partly because this is the first time the issue has been raised, and because it's such an opaque result. Describing / understanding the current functionality is simple: "Containers will always use their current content for hit checks, ignoring their cache". Explaining the way it works with this "fix" would take a blog post.

I'm closing this for now, but I'm open to being convinced it's worth implementing.

For future reference, here's the change to `Container._getObjectsUnderPoint`
`(!hitArea && child instanceof Container)` --> `(child instanceof Container && !(hitArea || (mouse && child.cacheCanvas && (activeListener || child._hasMouseEventListener()))))`

**Comment by danzen** [comment]
Ah - solved it on my side... I was using a Shape with a fill color of "0" for some reason and again, for some reason, this seems to be hit and miss!  Solved it with a proper color.  So ignore my comment directly above.  Not sure if the initial issue is solved but we have made it this far!  I tried the Grant Skinner code https://github.com/CreateJS/EaselJS/issues/1000#issuecomment-442253182 but it did not work.  Since, I solved my current problem, I just took the Grant code back out.
