### ISSUE TITLE
NEXT version breaks disable touch on OSX Chrome Version 70.0.3538.110 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by Johnafriedman** [CreateJS/EaselJS#1002]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [ ] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 
Master NEXT

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):
window.PointerEvent is defined in OSX Chrome so Touch.disable is misidentifying IE. 
IE_disable attempts to refer to stage.__touch.f when __touch is undefined causing an exception

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):
OSX 10.14.2 (18C54)
Chrome Version 70.0.3538.110 (Official Build) (64-bit)

* Do you know of any workarounds?

Works on Safari

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

Found this problem while addressing bug #997 with Chromebook Touch Screen

**Comment by danzen** [comment]
Hi @Johnafriedman  if you get a chance - can you test this page for me: https://zimjs.com/explore/drag.html on OSX touch screen and see if you get:
1. The numbers changing as you press drag on the red box.  
2. The black circle should drag.  
3. The triangle just captures mouse down values (not drag).
Thanks!
