### ISSUE TITLE
cache method fails in NEXT version installed with NPM

### ISSUE THREAD

**Issue by DavidCasillasRivero** [CreateJS/EaselJS#1004]
### TODO
- [X] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

Bug

- [X] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

Yes, only [one topic](https://github.com/CreateJS/EaselJS/issues/424) found with the error `too much recursion`  but seems unrelated unrelated.

- [X] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

Yes the problem happens in the last version.

### Issue Details
* Version used: 

The problem happens in the NEXT version of the library downloaded with npm.

` "@createjs/easeljs": "^2.0.0-beta.4"`
Using `dist/easel-NEXT.js` file.

The  problem is not happening in non NEXT versions.

The  problem is not happening in NEXT version downloaded directly from current master branch (1.0.2). 

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

The method `Shape.cache` gives an `too much recursion` error.

You can test in your own [Painting demo](https://createjs.com/demos/easeljs/curveto), adding a cache instruction to the drawingCanvas object:

    drawingCanvas.cache(0, 0, 600, 600); 

```
createCanvas https://localhost:3000/easeljs-NEXT.js:2558:4
createCanvas https://localhost:3000/easeljs-NEXT.js:2566:10
createCanvas https://localhost:3000/easeljs-NEXT.js:2566:10
createCanvas https://localhost:3000/easeljs-NEXT.js:2566:10
createCanvas https://localhost:3000/easeljs-NEXT.js:2566:10
...
...
```

I have created a [Code pen](https://codepen.io/david-casillas/pen/vvgJqq?editors=1011#0) with the library downloaded with `npm` and the code in your demo, adding the code below. If you open developer tools you can see the error. Removing the code fixes the issue:

This is line 6325 in js:

    // BUG
    drawingCanvas.cache(0, 0, 100, 100);  

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

 Tested with Firefox Quantum 64.0 and Version 69.0.3497.100 (Official Build) (64-bit) in Ubuntu 16.

* Do you know of any workarounds?

Use a library non downloaded from npm.
