### ISSUE TITLE
Single tap behaves as double tab on mobile

### ISSUE THREAD

**Issue by nidhinid** [CreateJS/EaselJS#1020]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [ ] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
open the attached html on mobile browser and test this - With the square button in frame 2, if you tap on it, then a popup will show. Click ok, and then the same popup appears, as if I clicked on it a second time. This should not happen ,single click is behaving like double click .This works fine on desktop browser.
or
[CreateJsIssue.zip](https://github.com/CreateJS/EaselJS/files/3033530/CreateJsIssue.zip)

1.create a canvas doc in animate ,create some button in different frames 
2.add event listener to enable touch event
3.test movie on mobile browser
Result:On desktop browser everything work fine ,when tested on mobile browser
every time I tap once, it acts like I tapped two times in rapid succession. If I have one button in one frame, tap the button to go to another frame, and a second button is in the same place as the first button from the previous frame, the second button will automatically be tapped also, even though I did not physically do this.

Expected : Single tap should work as single click only not double click
