### ISSUE TITLE
imageSmoothingEnabled not being applied to Sprites

### ISSUE THREAD

**Issue by FireController1847** [CreateJS/EaselJS#1026]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 

EaselJS 1.0.0

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

I'm not sure if this is specifially with "imageSmoothingEnabled" or if it's an issue with "snapToPixelEnabled," but as you can see in [this video](https://imgur.com/eDTVLdM) (sorry about the audio, had music on), using the browser to scale up and down works great, however when I input a scaleX or scaleY it fails. Previously I had used bitmaps for every tile, but I recently switched over to a SpriteSheet & Sprites. It worked perfectly with bitmaps, but it does not work at all with sprites (you can see it gets blurry).

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

Microsoft Edge | 75.0.139.1 (Official build) dev (64-bit)
Windows 10 OS Version 1809 (Build 17763.437)
(Issue persits in Google Chrome)
Google Chrome | 73.0.3683.103 (Official Build) (64-bit) (cohort: Stable)

* Do you know of any workarounds?

Nope, not other than literally scaling/resizing the canvas itself by either zooming or setting its width and height using CSS.

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

Unfortunately I can't really provide an example code, just the MP4.
