### ISSUE TITLE
How to use in React with npm ?

### ISSUE THREAD

**Issue by pxim** [CreateJS/EaselJS#1047]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [ ] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
 I want to use createjs in React with npm. But i don't know how to do .
 Is there a example ?

**Comment by danzen** [comment]
I've bumped into a few people using CreateJS within React.  I have some messages out...

**Comment by pxim** [comment]
I have solved the problem. Use my npm
https://www.npmjs.com/package/createjs-libs
`npm i createjs-libs`

**Comment by danzen** [comment]
Great - cheers.  I wonder if what you did was similar to what we did a while back - https://www.npmjs.com/package/@danzen/createjs - I will check yours out at some point, and you are welcome to try mine to see if it works too!

**Comment by pxim** [comment]
> Great - cheers. I wonder if what you did was similar to what we did a while back - https://www.npmjs.com/package/@danzen/createjs - I will check yours out at some point, and you are welcome to try mine to see if it works too!

OK, I'll try. Thank you.
