### ISSUE TITLE
Dragger not working on win10, Edge browser using touch

### ISSUE THREAD

**Issue by vkadri** [CreateJS/EaselJS#965]
### TODO
- [ ] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.
  - Bug
- [ ] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!
  - Did not find any related issue
- [ ] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?
  - Yes
- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!
    - N/A

### Issue Details
* Version used (Ex; 1.0): 
https://www.createjs.com/demos/easeljs/DragAndDrop.html

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

Draggers are not movable 

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

Windows 10 touch

,  Edge 42.17134.1.0

* Do you know of any workarounds?

No

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

https://www.createjs.com/demos/easeljs/DragAndDrop.html

**Comment by lannymcnie** [comment]
I believe the drag-and-drop for Edge was solved in September 2018, and is available in EaselJS NEXT.

I am going to close this issue, please feel free to reopen it if you can reproduce in the latest version.
