### ISSUE TITLE
 ScaleBitmap: Example code of README.md is not correct

### ISSUE THREAD

**Issue by FumioNonaka** [CreateJS/EaselJS#986]
### TODO
- [x] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [x] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [x] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 
EaselJS 1.0.0

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):
[README.md](https://github.com/CreateJS/EaselJS/tree/master/extras/ScaleBitmap)
Example
```
sb.setDrawSize
```
Two arguments, width and height, are needed.

**Comment by lannymcnie** [comment]
Thanks @FumioNonaka! Fixed in GitHub.
