### ISSUE TITLE
2.0.0-beta.2 fails to new Stage

### ISSUE THREAD

**Issue by MarvinWilliam** [CreateJS/EaselJS#987]
### TODO
- [x] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [x] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 
2.0.0-beta.2

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

```javascript
import { Stage } from '@createjs/easeljs';

export default class Canvas {
    constructor() {
        this.stage = new Stage('canvasId');
    }
}
```

Error:
```
easeljs.module.js:1904 Uncaught TypeError: Illegal constructor
    at createCanvas (easeljs.module.js:1904)
    at Object../node_modules/@createjs/easeljs/dist/easeljs.module.js (easeljs.module.js:3160)
    at __webpack_require__ (bootstrap 8cba5b6e973429fc89a0:678)
```

code where throw error
```javascript
function createCanvas(width = 1, height = 1) {
  let c;
  if (window.createjs !== undefined && window.createjs.createCanvas !== undefined) {
    c = window.createjs.createCanvas();
  }
  if (HTMLCanvasElement) {
    // this line throw error "Illegal constructor"
    c = new HTMLCanvasElement();
  }
  if (c !== undefined) {
    c.width = width;
    c.height = height;
    return c;
  }
  throw "Canvas not supported in this environment.";
}

```

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

* Do you know of any workarounds?
HTMLCanvasElement is sub interface of HTMLElement, it should not be used as constructor

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by MarvinWilliam** [comment]
This my pr for this issue.
[https://github.com/CreateJS/EaselJS/pull/988#issue-219197170](https://github.com/CreateJS/EaselJS/pull/988#issue-219197170)

**Comment by tehvgg** [comment]
Fixed in beta.4
