### ISSUE TITLE
Dynamic Text bounds not working after cache. Setbounds cannot be used as the text is dynamic

### ISSUE THREAD

**Issue by joseph-olivemultimedia** [CreateJS/EaselJS#990]
Iam building a text scroller with Mask and i cannot get the dynamic text bounds, i saw other solutions in this blog, where setBounds would be a solution. But for the dynamic texts, we cannot set the height without getbounds. I think its a bug. 

Im using createjs 1.0 version. 

### TODO
- [x] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [x] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [x] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0): 

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

* Do you know of any workarounds?

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.
