### ISSUE TITLE
2.0 branch can't be built

### ISSUE THREAD

**Issue by keroxp** [CreateJS/EaselJS#993]
### TODO
- [x] Is this a question or bug? [Stack Overflow](https://stackoverflow.com/questions/tagged/createjs) is a much better place to ask any questions you may have.

- [x] Did you search the [issues](https://github.com/CreateJS/EaselJS/issues) to see if someone else has already reported your issue? If yes, please add more details if you have any!

- [x] If you're using an older [version](https://github.com/CreateJS/EaselJS/blob/master/VERSIONS.txt), have you tried the latest?

- [ ] If you're requesting a new feature; provide as many details as you can. Why do you want this feature? Do you have ideas for how this feature should be implemented? Pseudocode is always welcome!

### Issue Details
* Version used (Ex; 1.0):2.0

* Describe whats happening (Include any relevant console errors, a [Gist](https://gist.github.com/) is preferred for longer errors):

2.0 branch can't be built on my machines (tried in several different environments).

At first, just after cloning, `npm install` failed:
```
➜  EaselJS git:(2.0) npm install
npm ERR! code E404
npm ERR! 404 Not Found: @createjs/docs@^2.0.0-beta.1
```

After deleting `@createjs/docs@^2.0.0-beta.1` from `devDependencies`, npm installation finished (partially failed) successfully, and warning was shown:

```
found 173 vulnerabilities (81 low, 79 moderate, 13 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Next, running `npm run build` failed:

```
➜  easelJS git:(2.0) ✗ npm run build

> @createjs/easeljs@2.0.0-beta.2 build /Users/sakurai/Development/EaselJS
> cd node_modules/@createjs/build && gulp build

sh: gulp: command not found

```

Next, changed npm script like this:
```
"build": "cd node_modules/@createjs/build && $(npm bin)/gulp build",
```

At the last, I got unresolvable error:

```
➜  easelJS git:(2.0) ✗ npm run build

> @createjs/easeljs@2.0.0-beta.2 build /Users/sakurai/Development/EaselJS
> cd node_modules/@createjs/build && $(npm bin)/gulp build

[15:00:25] Failed to load external module @babel/register
[15:00:25] Requiring external module babel-register
/Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328
        throw e;
        ^

Error: Options {"loose":true} passed to /Users/sakurai/Development/EaselJS/node_modules/babel-preset-env/lib/index.js which does not accept options. (While processing preset: "/Users/sakurai/Development/EaselJS/node_modules/babel-preset-env/lib/index.js") (While processing preset: "/Users/sakurai/Development/EaselJS/node_modules/babel-preset-env/lib/index.js")
    at /Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:314:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/sakurai/Development/EaselJS/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/sakurai/Development/EaselJS/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/sakurai/Development/EaselJS/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/sakurai/Development/EaselJS/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:598:32)
```

* OS & Browser version *(Please be specific)* (Ex; Windows 10 Home, Chrome 62.0.3202.94):

macOS 10.14, node 10.12 , npm 6.4.1

* Do you know of any workarounds?

I've resolved the error above by editing `@createjs/build` in `node_modules` directly upgrading `babel` related resources into babel7 but not understood what happened. 
Could you consider checking the current project build setting is valid? and upgrading babel into version together.

* Provide any extra details that will help us fix your issue. Including a link to a [CodePen.io](https://codepen.io) or [JSFiddle.net](https://jsfiddle.net) example that shows the issue in isolation will greatly increase the chance of getting a quick response.

**Comment by Lange** [comment]
I would also like to build the `2.0` branch so that I can open PRs for some simple fixes, but am running into the same problems.

**Comment by Lange** [comment]
Ah, I think part of the problem is that `@createjs/build` marks _all_ of its dependencies as `devDependencies`. Thus, when `@createjs/build` is installed by `@createjs/EaselJS`, none of `@createjs/build`'s dependencies get installed.

I'm working on a branch of `@createjs/build` which addresses this, will open a PR if things work out.

**Comment by tehvgg** [comment]
This should be resolved as of beta.4 (build dependency is in beta.5)
